[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["梁文亮 <liangwenliang@corp.netease.com>"]
edition = "2018"
description = "A Open Learing Exercise"
license = "MIT"

[dependencies]
rand = "0.6.5"

[profile.release]
panic = 'abort'
opt-level = 3

[profile.dev]
opt-level = 0